# Configuration for librarian-puppet. For example:

forge "http://forge.puppetlabs.com"

mod "puppetlabs/stdlib"
mod "example42/yum"
mod "andyshinn/atomic"
mod "example42/puppi"
mod "example42/mysql"
mod "example42/php"
mod "rafaelfc/pear"
mod "puppetlabs/apache"
mod "erikwebb/drush"
#mod "erikwebb/drupal"


# mod "apt",
# :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

#mod "erikwebb/drupal",
# :git => "git://github.com/paulhudson/erikwebb-drupal"