# Configuration for librarian-puppet. For example:
#
 forge "http://forge.puppetlabs.com"
#
mod "puppetlabs/stdlib"
mod "example42yum"
mod "andyshinn/atomic"
mod "example42/puppi"
mod "example42/mysql"
mod "example42/php"
mod "rafaelfc/pear"
mod "example42/apache"
#
# mod "apt",
# :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
#
# mod "stdlib",
# :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"